package ptypes

// CheckPoint:  proof generated by a node to prove that a state is correct
// and has been reached by at least f+1 correct nodes.
type CheckPoint struct {
	Seq          int             // the sequence of checkpoint
	CPMsgs       []*PMsg         // the proof, which consist of 2f + 1 checkpoint message
	WaitSeq      int             // a sequence which node currently waiting for a checkpoint message corresponding to
	CPMsgsBuffer map[int][]*PMsg // checkpoint messages received that are greater than the previous checkpoint sequence number but have not yet been committed
}
